name: blcs-app
ingress:
  rules:
  - match:
      path:
        prefix: /
    component:
      name: dashboard
services:
- name: bot
  dockerfile_path: discord_bot/Dockerfile
  source_dir: /
  github:
    repo: RJUNCC/buckystyle_league_championship_series
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  # No http_port for bot service
  envs:
  - key: DISCORD_TOKEN
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET

- name: dashboard
  dockerfile_path: dashboard/Dockerfile
  source_dir: /
  github:
    repo: RJUNCC/buckystyle_league_championship_series
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: PORT
    value: "8080"
    scope: RUN_TIME
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET