[tool.poetry]
name = "buckystyle-league"
version = "0.1.0"
description = "Buckystyle League Championship Series Data Analysis and Discord Bot"
authors = ["RJUNCC <20bigal04@ryeguytech.com>"]
license = "MIT"
readme = "README.md"

# Define the packages to be included in the distribution
packages = [
    { include = "config" },
    { include = "discord_bot" },
    { include = "database" },
    { include = "scripts" },
    { include = "models" },
    # Add other packages as needed
]

[tool.poetry.dependencies]
python = "^3.11"

# Core Dependencies
pandas = "^2.2.3"
numpy = "^2.1.3"
requests = "^2.32.3"
python-dotenv = "^1.0.1"
sqlalchemy = "^2.0.36"
psycopg2-binary = "^2.9.10"
matplotlib = "^3.9.2"
plotly = "^5.24.1"
dataframe-image = "^0.2.6"
seaborn = "0.13.2"
scipy = "1.14.1"

# Discord Bot Dependencies
discord-py = "^2.4.0"  # Corrected from 'discord-py' to 'discord.py'

# Streamlit
streamlit = "^1.25.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
flake8 = "^7.1.1"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
