name: discord-bot
services:
- name: bot
  dockerfile_path: discord_bot/Dockerfile
  source_dir: /discord_bot  # KEY CHANGE: Point to subdirectory
  github:
    repo: RJUNCC/buckystyle_league_championship_series
    branch: main
    deploy_on_push: true
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  envs:
  - key: DATABASE_URL
    value: sqlite:////app/data/scheduling.db
    scope: RUN_TIME
  - key: PORT
    value: "8080"
    scope: RUN_TIME
  - key: DISCORD_TOKEN
    scope: RUN_TIME
    type: SECRET