name: Daily Bot Task

on:
  schedule:
    - cron: "* 1 * * *" # Runs daily at 1:00 am UTC
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11" # or your preferred version

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root

      - name: Fetch data, filter data, and create images and stats
        env:
          TOKEN: ${{ secrets.TOKEN }}
          BALLCHASING_TOKEN: ${{ secrets.BALLCHASING_TOKEN }}
          CHANNEL_ID3: ${{ secrets.CHANNEL_ID3 }}
          PLAYOFF_GROUP_URL: ${{ secrets.PLAYOFF_GROUP_URL }}
        run: |
          cd scripts
          poetry run playoff_stats.py

      - name: Send images to discord channel
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TOKEN: ${{ secrets.TOKEN }} # Use your Discord token secret here
        run: |
          cd scripts
          poetry run send_images.py
