name: Daily Bot Task

on:
  schedule:
    - cron: "0 1 * * *" # 1:00 AM UTC
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        uses: SpicyPizza/create-envfile@v2
        with:
          # Map secrets to .env variables
          envkey_DEBUG: "false" # Optional example
          envkey_TOKEN: ${{ secrets.TOKEN }}
          envkey_DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          envkey_CURRENT_GROUP_ID: ${{ secrets.CURRENT_GROUP_ID }}
          envkey_PLAYER_CHANNEL_ID: ${{ secrets.PLAYER_CHANNEL_ID }}
          envkey_TEAM_CHANNEL_ID: ${{ secrets.TEAM_CHANNEL_ID }}
          # Action configuration
          file_name: .env
          directory: discord_bot
          fail_on_empty: true
          sort_keys: true

      - name: Set up Python environment
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Setup python
        run: uv python install

      - name: Run processing
        run: uv run --with 'matplotlib' scripts/process.py

      - name: Send Discord images
        run: uv run discord_bot/cogs/send_images.py
