name: Daily Bot Task

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 1:00 am ETC
  workflow_dispatch:
    inputs:
      trigger-type:
        description: "Type of trigger (e.g., manual)"
        required: false

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          # - "3.9"
          # - "3.10"
          - "3.11"
          # - "3.12"

    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install astral uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version}}

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Setup python
        run: uv python install

      - name: Fetch data, filter data, and create images and stats
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CURRENT_GROUP_ID: ${{ secrets.CURRENT_GROUP_ID }}
          TRIGGER_TYPE: ${{ github.event.inputs.trigger-type }}

        run: |
          uv run --with 'matplotlib' scripts/process.py

      - name: Send images to discord channel
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          PLAYER_CHANNEL_ID: ${{ secrets.PLAYER_CHANNEL_ID }} # Use your Discord token secret here
          TEAM_CHANNEL_ID: ${{ secrets.TEAM_CHANNEL_ID }} # Use your Discord token secret here
        run: |
          uv run discord_bot/cogs/send_images.py
