name: Daily Bot Task

on:
  schedule:
    - cron: "0 1 * * *" # Fixed cron syntax (runs at 1:00 AM UTC daily)
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    # Removed matrix since you're only using 3.11
    environment: production # Add environment protection

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore .env from secret
        run: |
          echo "${{ secrets.DOTENV_CONTENT }}" | base64 --decode > .env
          # Verify .env was created (without exposing secrets)
          [ -s .env ] && echo ".env file restored" || exit 1

      - name: Set up Python environment
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt --all-extras
          uv pip install matplotlib  # Explicit installation

      - name: Run processing
        run: uv run scripts/process.py
        env:
          # Load all variables from .env automatically
          $(cat .env | xargs)

      - name: Send Discord images
        run: uv run discord_bot/cogs/send_images.py
        env: $(cat .env | xargs)
