name: Daily Bot Task

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore .env from secret
        run: |
          echo "${{ secrets.DOTENV_CONTENT }}" | base64 --decode > .env
          [ -s .env ] || exit 1

      - name: Load environment variables
        run: |
          echo "Loading .env file"
          while IFS= read -r line; do
            if [[ "$line" =~ ^[A-Za-z_][A-Za-z0-9_]*= ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < .env

      - name: Set up Python environment
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.11"

      - name: Install project
        run: uv sync --all-extras --dev

      - name: Setup python
        run: uv python install

      - name: Run processing
        run: uv run --with 'matplotlib' scripts/process.py

      - name: Send Discord images
        run: uv run discord_bot/cogs/send_images.py
