name: Daily Bot Task

on:
  schedule:
    - cron: "0 5 * * *" # Runs daily at 1:00 am ETC
  workflow_dispatch:
    inputs:
      trigger-type:
        description: "Type of trigger (e.g., manual)"
        required: false

jobs:
  run-daily-task:
    name: Run Daily Data Processing
    runs-on: ubuntu-latest
    # Ensure this job only runs on the schedule, not on every push
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install astral uv
        uses: astral-sh/setup-uv@v1
        with:
          python-version: '3.11'

      - name: Install project dependencies
        run: uv pip sync --all-extras

      - name: Fetch, process data, and create images
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CURRENT_GROUP_ID: ${{ secrets.CURRENT_GROUP_ID }}
        run: |
          uv run python scripts/process.py
      
      - name: Send images to Discord
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          PLAYER_CHANNEL_ID: ${{ secrets.PLAYER_CHANNEL_ID }}
          TEAM_CHANNEL_ID: ${{ secrets.TEAM_CHANNEL_ID }}
        run: |
          uv run python discord_bot/cogs/send_images.py
