name: Run Predictions

on:
  schedule:
    - cron: "0 14 * * *" # Runs daily at 14:00 UTC
  workflow_dispatch:

jobs:
  run_predictions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - name: Build Rust project
        run: |
          cd rust_predictions
          cargo build --release

      - name: Run Rust predictions
        run: |
          ./rust_predictions/target/release/rust_predictions
